services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: drift-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0

  streamlit:
    image: python:3.10-slim
    container_name: drift-ui
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./:/app
    command: >
      bash -c "pip install -r requirements.txt &&
               streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - api
      - mlflow
