FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY inference/ inference/
COPY models/trained/ models/trained/

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "inference.app:app"]